# This is a config for E2B sandbox template.
# You can use template ID (hmtuc9w2baapk11lx659) or template name (vibe-nextjs-try-3) to create a sandbox:

# Python SDK
# from e2b import Sandbox, AsyncSandbox
# sandbox = Sandbox.create("vibe-nextjs-try-3") # Sync sandbox
# sandbox = await AsyncSandbox.create("vibe-nextjs-try-3") # Async sandbox

# JS SDK
# import { Sandbox } from 'e2b'
# const sandbox = await Sandbox.create('vibe-nextjs-try-3')

team_id = "47292e59-733e-4fd7-8ab0-b389c0d6bf72"
start_cmd = "bash /compile_page.sh"
dockerfile = "e2b.Dockerfile"
template_name = "vibe-nextjs-try-3"
template_id = "hmtuc9w2baapk11lx659"
